version: "3"
services:
  api:
    container_name: james-dash-api
    restart: always
    image: node:16
    working_dir: /usr/application/james-dash-api
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27018/clean-node-api
    volumes:
      - ./dist/:/usr/application/james-dash-api/dist/
      - ./package.json:/usr/application/james-dash-api/package.json
    ports:
      - "8080:8080"
      - "9222:9222"
